### ISSUE TITLE
Top1 accuracy results

### ISSUE THREAD

**Issue by weishengchong** [hpnair/18663_Project_FBNet#1]
@hpnair, @SaiVineethKalluruSrinivas, @vinayvid,

Thanks for sharing your great works!

May I know check with you about the following?
1)What RasberryPi model is used for rpi_speed.txt measurement? eg. Pi 2/3/3b? May I assume CPU frequency and number of threads are not changed from the Pi's default?

2)What intel processor used for speed_cpu.txt measurement?

BTW, I found your code includes Imagenet training, if you have completed its training, is it possible to share your Top1 accuracy results & its CPU time?
https://github.com/AnnaAraslanova/FBNet said it takes 27*8 GPU hours to train  FBnet for Imagenet:)

Thanks

**Comment by SaiVineethKalluruSrinivas** [comment]
Hi, 
Thank you for contacting.
We have used Raspberry Pi 3B. We have used defaults only.
We have used Intel i5 processor (Macbook pro 2015 model). Feel free to use measure_speed.py to get the latency lookup table for your target device.
The stride values have been changed to include for CIFAR-10 and not for Imagenet. Feel free to change the stride values (you can use stride values mentioned in the paper). 
For training on CIFAR-10 it took 6 GPU hours to converge over 90 epochs. 
However, I am guessing it would take around 10-12 GPU hours.
We used XSEDE PSC NVIDIA Tesla P100 GPUs for training.

We will soon update the repo with our results.

**Comment by weishengchong** [comment]
Thanks @SaiVineethKalluruSrinivas for sharing the infor.
